baseURL = "https://movietheme.muthukrishnan.dev/"

title = "movie review"

languageCode = "en-us"
summaryLength = 10
enableEmoji = true
paginate = 5
copyright = "&copy; {year} {name}. All rights reserved." # {year}, {name} supported

theme = "movie-theme"
