[[header]]
    name = "Discover"
    identifier = "discover"
    title = "discover"
    url = "discover"
    weight = 1

[[header]]
    name = "Home"
    identifier = "d_home"
    title = "discover"
    url = "/discover"
    weight = 1
    parent = "discover"

[[header]]
    name = "By Actors"
    identifier = "d_actors"
    title = "actors"
    url = "/actors"
    weight = 2
    parent = "discover"

[[header]]
    name = "Top"
    identifier = "top"
    title = "top"
    url = "/top"
    weight = 2

[[header]]
    name = "Movies"
    identifier = "Movies"
    title = "Movies"
    url = "/Movies"
    weight = 3

[[header]]
    name = "TV Shows"
    identifier = "TV Shows"
    title = "TV Shows"
    url = "/tvshows"
    weight = 4

[[header]]
    name = "Editorials"
    identifier = "editorials"
    title = "editorials"
    url = "/editorials"
    weight = 5

[[header]]
    name = "Reviews"
    identifier = "reviews"
    title = "reviews"
    url = "/reviews"
    weight = 6

[[header]]
    name = "Why?"
    identifier = "about"
    title = "about"
    url = "/about"
    weight = 7
    
[[footer]]
    name = "Home"
    identifier = "home"
    title = "home"
    url = "/"
    weight = 1

[[footer]]
    name = "About"
    identifier = "about"
    title = "about"
    url = "/about"
    weight = 2
