[[mounts]]
  source = "content_index"
  target = "content"
[[mounts]]
  source = "content_meta"
  target = "content"
[[mounts]]
  source = "content_title"
  target = "content"
[[mounts]]
  source = "content"
  target = "content"

[[mounts]]
  source = "content_sample"
  target = "content"
