[[mounts]]
  source = "content"
  target = "content"
[[mounts]]
  source = "metacontent/meta"
  target = "content"
[[mounts]]
  source = "metacontent/special"
  target = "content"
[[mounts]]
  source = "metacontent/taxonomies"
  target = "content"
  