[[mounts]]
  source = "content"
  target = "content"
[[mounts]]
  source = "indexcontent/special"
  target = "content"
[[mounts]]
  source = "indexcontent/meta"
  target = "content"
[[mounts]]
  source = "metacontent/taxonomies"
  target = "content"
[[mounts]]
  source = "metacontent/titles"
  target = "content"
