[Info]
  ShortTitle = "moviereview"
  Subtitle = "my reviews"
  Description = "long description of the site"
  Logo = "logo.png" # store in static/images

  # used as substitute for baseimageurl: in poster param in movies, tvshows
  BaseImageURL = "" #https://example.com

[Controls]
  # option to ignore the poster params in posts and use NoPoster for all cases
  # this overrides all other poster configs
  DoNotShowPoster = false

  # in case no poster exist in local directory case (if BaseImageURL is empty string)
  # use display noposter.png instead of throwing error
  UseNoPoster = true


[Meta]
  MainScore = "Main Score"
  CustomScores = ["Custom1", "Custom2"]

  # advanced configs
  DiscoverList = ["actors", "creators", "directors", "writers", "musicdirectors", "cinematographers", "genres"]
  TopList = ["movies", "tvshows"]

  # adds text 's Filmography to all these
  FilmographyList = ["actors", "writers", "creators", "directors", "musicdirectors", "cinematographers"]

# advanced configs
[Meta.TitleCrewList]
  movies = ["actors", "directors", "writers", "musicdirectors", "cinematographers"]
  tvshows = ["actors", "creators"]

[Meta.TitleMetaList]
  movies = ["genres", "plottags"]
  tvshows = ["genres", "plottags"]

[Meta.DetailListLimit]
  actors = 4 # no of actors to display in Cast & Crew

[Meta.Pagination]
  # default will be 8
  actors = 8
  writers = 8
  directors = 8
  musicdirectors = 8
  cinematographers = 8
  movies = 8
  tvshows = 8

  editorials = 10
  reviews = 10
  
  genres = 100
  plottags = 8
  tags = 10
  
  top = 10
  discover = 10

[Social]
  Email = "Your_Email_ID"
  Facebook = "Your_Facebook_ID"
  Twitter = "Your_Twitter_ID"
  Instagram = "Your_Instagram_ID"
  Youtube = "Your_Youtube_ID"
  Reddit = "u/Your_Reddit_ID"

[Style]
  # Custom Css/Js/Fonts
  # CSS = ["css/main.css"] # place custom .css files inside assets folder
  # JS = ["js/main.js"] # place custom .js files inside assets folder
  FontsLink = ["https://fonts.googleapis.com/css?family=Open+Sans:300,400,700"] # only online fonts
  FontsPreconnect = ["https://fonts.gstatic.com"]
  FontsName = ["Open Sans"]

[Favicon]
  # store favicons in static/favicons folder
  icon = "favicon.ico" # favicon
  icon16 = "favicon-16x16.png"
  icon32 = "favicon-32x32.png"
  icon192 = "android-chrome-192x192.png"
  icon512 = "android-chrome-512x512.png"
  appleTouch = "apple-touch-icon.png"

[Manifest]
  themeColor = "#ffffff"
  backgroundColor = "#ffffff"
  display = "standalone"
  orientation = "portrait"

[Config]
  # header
  ShowSiteLogo = false
  ShowSiteTitle = true # if site logo is not present, title is displayed by default
  ShowSiteSubtitle = true # available only if ShowSiteTitle is enabled
 
  # navigation
  ShowHeaderNav = true
  ShowFooterNav = true # disables the footer, both social and navigation
  ShowSocialFooterNav = true # enable this to show social nav instead of navigations

  # social icons
  ShowSocialIcons = true # enable this to show social icons instead of text
  ShowColorIcons = true # enable this to colorful social icons
  
  # home page
  ShowSummaryInPostList = false
  # ShowStarredIcon = true
  