[Info]
  ShortTitle = "blog"
  Subtitle = "my blog"
  Description = "long description about site"
  Logo = "logo.png" # store in static/images

[Meta]
  MainScore = "Main Score"
  CustomScores = ["Custom1", "Custom2"]
  TopListCount = 10
  DiscoverListCount = 10

  # advanced configs
  CastCrewList = ["actors", "writers", "directors", "musicdirectors", "cinematographers"]
  MovieDetailList = ["genres", "plottags"]
  # if any meta above is not defined for movies or tvshows
  # meta in below list will be considered optional and will not throw error
  OptionalList = ["cinematographers", "musicdirectors", "plottags"]
  
  TopList = ["movies", "tvshows"]

[Meta.DetailListLimit]
  actors = 4 # no of actors to display in Cast & Crew

[Social]
  Email = "Your_Email_ID"
  Facebook = "Your_Facebook_ID"
  Twitter = "Your_Twitter_ID"
  Instagram = "Your_Instagram_ID"
  Youtube = "Your_Youtube_ID"
  Reddit = "u/Your_Reddit_ID"

[Style]
  # Custom Css/Js/Fonts
  # CSS = ["css/main.css"] # place custom .css files inside assets folder
  # JS = ["js/main.js"] # place custom .js files inside assets folder
  FontsLink = ["https://fonts.googleapis.com/css?family=Open+Sans:300,400,700"] # only online fonts
  FontsPreconnect = ["https://fonts.gstatic.com"]
  FontsName = ["Open Sans"]

[Favicon]
  # store favicons in static/favicons folder
  icon = "favicon.ico" # favicon
  icon16 = "favicon-16x16.png"
  icon32 = "favicon-32x32.png"
  icon192 = "android-chrome-192x192.png"
  icon512 = "android-chrome-512x512.png"
  appleTouch = "apple-touch-icon.png"

[Manifest]
  themeColor = "#ffffff"
  backgroundColor = "#ffffff"
  display = "standalone"
  orientation = "portrait"

[Config]
  # header
  ShowSiteLogo = false
  ShowSiteTitle = true # if site logo is not present, title is displayed by default
  ShowSiteSubtitle = true # available only if ShowSiteTitle is enabled
 
  # navigation
  ShowHeaderNav = true
  ShowFooterNav = true # disables the footer, both social and navigation
  
  # home page
  ShowSummaryInPostList = false
  ShowStarredIcon = true
  
  # social icons
  ShowSocialFooterNav = true # enable this to show social nav instead of navigations
  ShowSocialIcons = true # enable this to show social icons instead of text
  ShowColorIcons = true # enable this to colorful social icons
