[Info]
  Tagline = "my reviews"
  Description = "long description of the site"
  Logo = "logo.png" # store in static/images
  coverImage = "cover.png" # store in static/images

  # optional image to show in 404 page, will not throw error, only shows a warning if image not found
  image404 = "404.jpg" # store in static/images
  image404AttrText = "Constructocat by jasoncostello" # optional image alt text
  image404AttrLink = "https://github.com/jasoncostello" # optional image alt link

  # used as substitute for baseimageurl: in poster param in movies, tvshows
  BaseImageURL = "" #https://example.com

  DateFormat = "January 2, 2006"

[Social]
  Email = "Your_Email_ID"
  Facebook = "Your_Facebook_ID"
  # Twitter = "Your_Twitter_ID"
  Instagram = "Your_Instagram_ID"
  Youtube = "Your_Youtube_ID"
  Reddit = "u/Your_Reddit_ID"

[Style]
  # Custom Css/Js/Fonts
  # CSS = ["css/main.css"] # place custom .css files inside assets folder
  # JS = ["js/main.js"] # place custom .js files inside assets folder
  FontsLink = ["https://fonts.googleapis.com/css?family=Open+Sans:300,400,700"] # only online fonts
  FontsPreconnect = ["https://fonts.gstatic.com"]
  FontsName = ["Open Sans"]

[Favicon]
  # store favicons in static/favicons folder
  icon = "favicon.ico" # favicon
  icon16 = "favicon-16x16.png"
  icon32 = "favicon-32x32.png"
  icon192 = "android-chrome-192x192.png"
  icon512 = "android-chrome-512x512.png"
  appleTouch = "apple-touch-icon.png"
  safariPinned = "safari-pinned-tab.svg"
  msTileImage = "mstile-144x144.png"

[Manifest]
  shortTitle = ""
  themeColor = "#ffffff"
  backgroundColor = "#ffffff"
  display = "standalone"
  orientation = "portrait"
  tileColor = "#ffffff"

[Controls]
  # header
  ShowSiteLogo = false
  ShowSiteTitle = true # if site logo is not present, title is displayed by default
  ShowSiteTagline = true # available only if ShowSiteTitle is enabled

  # navigation
  ShowHeaderNav = true
  ShowFooterNav = true # disables the footer, both social and navigation
  ShowSocialFooterNav = true # enable this to show social nav instead of navigations

  # social icons
  ShowSocialIcons = true # enable this to show social icons instead of text

  # home page
  ShowSummaryInPostList = false
  # ShowStarredIcon = true

  EnableRSS = false

  # option to ignore the poster params in posts and use NoPoster for all cases
  # this overrides all other poster configs
  DoNotShowPoster = false

  # in case no poster exist in local directory case (if BaseImageURL is empty string)
  # use display noposter.png instead of throwing error
  UseNoPoster = true

[Search]
  Enable = true # search index
  AppID = "AppID"
  SearchAPIKey = "SearchKey"
  IndexName = "IndexName"
  CountPerPage = 10
  IndexTypes = ["movies", "tvshows", "actors", "creators", "directors", "writers", "musicdirectors", "cinematographers"]

[ShareButton]
  # disable all
  Show = true

  Email = true
  Facebook = true
  Twitter = true
  Reddit = true
  Whatsapp = true
  Telegram = true

[Rating]
  MainScore = "Main Score"
  MainScoreSuffix = "%"
  CustomScores = ["Custom1", "Custom2"]
  CustomScoresSuffix = [" ", "%"]
  # Custom text look up for custom scores instead of suffix
  CustomScoreLookUp = [ {}, { 0 = "Very Bad", 1 = "Bad", 2 = "Okay", 3 = "Good", 4 = "Very Good", 5 = "Best"}]

[ReadMoreLinks]
  # these are places where you may ask user to read more about like privacy policy, disclaimer etc.,
  # All have three params Message, URL, LinkText and option to enable/disable them
  # display format
  # Message (LinkText)

  # Trailer, External Links, Poster, Ratings are supported now

[ReadMoreLinks.Poster]
  # default text which is shown when productions is not present in movies, tvshows meta post
  ShowInfo = true
  URL = "/disclaimer#fair-use"
  LinkText = "Fair Use"
  Message = "Respective Studio or Artist."

[ReadMoreLinks.Trailer]
  ShowInfo = true
  URL = "/disclaimer#trailer"
  LinkText = "Read Full Disclaimer"
  Message = """We do not own this video."""

[ReadMoreLinks.ExternalLinks]
  ShowInfo = true
  URL = "/disclaimer#external-links"
  LinkText = "Read Full Disclaimer"
  Message = """These links are being provided as a convenience and for informational purposes only."""

[ReadMoreLinks.TitleEndNote]
  ShowInfo = false
  URL = "/disclaimer#general"
  LinkText = "Here"
  Message = """All information provided are prone to error. If find any let us know"""

# Rating and ContentRating are special cases Message param is not needed

[ReadMoreLinks.Rating]
  # Link to detail post which explains your rating scores
  ShowInfo = true
  URL = "/about#ratings"
  LinkText = "more info on these scores"

[ReadMoreLinks.ContentRating]
  # Link to detail post which explains your rating scores
  ShowInfo = true
  URL = "/about#content-rating"
  LinkText = "more info"

# advanced configs
[MetaConfig]
  DiscoverList = ["actors", "creators", "directors", "writers", "musicdirectors", "cinematographers", "genres"]
  TopList = ["movies", "tvshows"]

  # adds text 's Filmography to all these
  FilmographyList = ["actors", "writers", "creators", "directors", "musicdirectors", "cinematographers"]

# advanced configs
[MetaConfig.TitleCrewList]
  movies = ["actors", "directors", "writers", "musicdirectors", "cinematographers"]
  tvshows = ["actors", "creators"]

[MetaConfig.TitleMetaList]
  movies = ["genres", "plottags"]
  tvshows = ["genres", "plottags"]

[MetaConfig.DetailListLimit]
  actors = 4 # no of actors to display in Cast & Crew
  plottags = 5

[MetaConfig.Pagination]
  # default will be 8
  actors = 10
  writers = 10
  directors = 10
  creators = 10
  musicdirectors = 10
  cinematographers = 10

  movies = 12 # need to be multiple of 4
  tvshows = 12 # need to be multiple of 4

  editorials = 10
  reviews = 10

  genres = 25
  reviewtags = 25
  plottags = 25
  tags = 25

  top = 10
  discover = 10

[MetaConfig.Ordering]
  actors = "alpha"               # available options: alpha, alphaDesc, date, dateDesc
  writers = "alpha"              # available options: alpha, alphaDesc, date, dateDesc
  directors = "alpha"            # available options: alpha, alphaDesc, date, dateDesc
  musicdirectors = "alpha"       # available options: alpha, alphaDesc, date, dateDesc
  cinematographers = "alpha"     # available options: alpha, alphaDesc, date, dateDesc
  creators = "alpha"             # available options: alpha, alphaDesc, date, dateDesc

  genres = "alpha"                  # available options: alpha, alphaDesc, date, dateDesc
  reviewtags = "alpha"              # available options: alpha, alphaDesc, date, dateDesc
  plottags = "alpha"                # available options: alpha, alphaDesc, date, dateDesc
  tags = "alpha"                    # available options: alpha, alphaDesc, date, dateDesc

  editorials = "dateDesc"   # available options: alpha, alphaDesc, date, dateDesc
  reviews = "dateDesc"      # available options: alpha, alphaDesc, date, dateDesc

  movies = "dateDesc"       # available options: date, dateDesc, release, releaseDesc, releaseYear, releaseYearDesc
  tvshows = "dateDesc"      # available options: date, dateDesc, release, releaseDesc, releaseYear, releaseYearDesc
