[Info]
  Tagline = "my reviews"
  Description = "long description of the site"
  Logo = "logo.png" # store in static/images
  coverImage = "cover.png" # store in static/images

  # used as substitute for baseimageurl: in poster param in movies, tvshows
  BaseImageURL = "" #https://example.com

  DateFormat = "January 2, 2006"

[Controls]
  # option to ignore the poster params in posts and use NoPoster for all cases
  # this overrides all other poster configs
  DoNotShowPoster = false

  # in case no poster exist in local directory case (if BaseImageURL is empty string)
  # use display noposter.png instead of throwing error
  UseNoPoster = true

[Disclaimer]
  # default text which is shown when productions is not present in movies, tvshows meta post
  ShowPoster = true
  PosterLink = "/disclaimer#copyrights"
  PosterLinkText = "Fair Use"
  PosterText = "Respective Studio or Artist."

  ShowTrailer = true
  TrailerLink = "/disclaimer#umbrae-velis-noctes-mutata"
  TrailerLinkText = "Read Full Disclaimer"
  TrailerText = """We do not own this video."""

  ShowExternal = true
  ExternalLink = "/disclaimer#external-links"
  ExternalLinkText = "Read Full Disclaimer"
  ExternalText = """These links are being provided as a convenience and for informational purposes only."""

  # Link to detail post which explains your rating scores
  ShowRating = true
  RatingLink = "/about#ratings"
  RatingLinkText = "more info on these scores"

[Meta]
  MainScore = "Main Score"
  MainScoreSuffix = "%"
  CustomScores = ["Custom1", "Custom2"]
  CustomScoresSuffix = [" ", "%"]

  CustomRatingLookUp = [ {}, { 0 = "Very Bad", 1 = "Bad", 2 = "Okay", 3 = "Good", 4 = "Very Good", 5 = "Best"}]

  # advanced configs
  DiscoverList = ["actors", "creators", "directors", "writers", "musicdirectors", "cinematographers", "genres"]
  TopList = ["movies", "tvshows"]

  # adds text 's Filmography to all these
  FilmographyList = ["actors", "writers", "creators", "directors", "musicdirectors", "cinematographers"]

# advanced configs
[Meta.TitleCrewList]
  movies = ["actors", "directors", "writers", "musicdirectors", "cinematographers"]
  tvshows = ["actors", "creators"]

[Meta.TitleMetaList]
  movies = ["genres", "plottags"]
  tvshows = ["genres", "plottags"]

[Meta.DetailListLimit]
  actors = 4 # no of actors to display in Cast & Crew
  plottags = 5

[Meta.Pagination]
  # default will be 8
  actors = 10
  writers = 10
  directors = 10
  musicdirectors = 10
  cinematographers = 10

  movies = 8
  tvshows = 8

  editorials = 10
  reviews = 10

  genres = 25
  reviewtags = 25
  plottags = 25
  tags = 25

  top = 10
  discover = 10

[Social]
  Email = "Your_Email_ID"
  Facebook = "Your_Facebook_ID"
  Twitter = "Your_Twitter_ID"
  Instagram = "Your_Instagram_ID"
  Youtube = "Your_Youtube_ID"
  Reddit = "u/Your_Reddit_ID"

[Style]
  # Custom Css/Js/Fonts
  # CSS = ["css/main.css"] # place custom .css files inside assets folder
  # JS = ["js/main.js"] # place custom .js files inside assets folder
  FontsLink = ["https://fonts.googleapis.com/css?family=Open+Sans:300,400,700"] # only online fonts
  FontsPreconnect = ["https://fonts.gstatic.com"]
  FontsName = ["Open Sans"]

[Favicon]
  # store favicons in static/favicons folder
  icon = "favicon.ico" # favicon
  icon16 = "favicon-16x16.png"
  icon32 = "favicon-32x32.png"
  icon192 = "android-chrome-192x192.png"
  icon512 = "android-chrome-512x512.png"
  appleTouch = "apple-touch-icon.png"
  safariPinned = "safari-pinned-tab.svg"
  msTileImage = "mstile-144x144.png"

[Manifest]
  shortTitle = ""
  themeColor = "#ffffff"
  backgroundColor = "#ffffff"
  display = "standalone"
  orientation = "portrait"
  tileColor = "#ffffff"

[Config]
  # header
  ShowSiteLogo = false
  ShowSiteTitle = true # if site logo is not present, title is displayed by default
  ShowSiteTagline = true # available only if ShowSiteTitle is enabled

  # navigation
  ShowHeaderNav = true
  ShowFooterNav = true # disables the footer, both social and navigation
  ShowSocialFooterNav = true # enable this to show social nav instead of navigations

  # social icons
  ShowSocialIcons = true # enable this to show social icons instead of text
  ShowColorIcons = true # enable this to colorful social icons

  # home page
  ShowSummaryInPostList = false
  # ShowStarredIcon = true

  EnableRSS = false
