includeNewer = false
threshold = 90
toLower = false

# Main Tags

[[indices]]
name = "tags"
weight = 80

[[indices]]
name = "reviewtags"
weight = 80

[[indices]]
name = "plottags"
weight = 80

# Main Data

[[indices]]
name = "actors"
weight = 70

[[indices]]
name = "creators"
weight = 70

[[indices]]
name = "directors"
weight = 70

# Major Indicies

[[indices]]
name = "genres"
weight = 50

# Less Important

[[indices]]
name = "cinematographers"
weight = 25

[[indices]]
name = "musicdirectors"
weight = 25

[[indices]]
name = "writers"
weight = 25

# Least

[[indices]]
name = "date"
weight = 10
